# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx
from objs import category_mgr

# begin wxGlade: dependencies
# end wxGlade

class CategoriesDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CategoriesDlg.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.__list = wx.CheckListBox(self, -1)
        self.__add = wx.Button(self, -1, "&Add")
        self.__modify = wx.Button(self, -1, "&Modify")
        self.__delete = wx.Button(self, -1, "&Delete")
        self.button_4 = wx.Button(self, wx.ID_OK, "")
        self.button_2 = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.__OnAddCategory, self.__add)
        self.Bind(wx.EVT_BUTTON, self.__OnModifyCategory, self.__modify)
        self.Bind(wx.EVT_BUTTON, self.__OnDeleteCategory, self.__delete)
        self.Bind(wx.EVT_BUTTON, self.__OnOK, self.button_4)
        # end wxGlade
        
        self.LoadCategories()

    # --------------------------------------------------------------------------
    def __set_properties(self):
        # begin wxGlade: CategoriesDlg.__set_properties
        self.SetTitle("Enter Song Categories")
        self.__list.SetMinSize((250, 260))
        self.__add.Enable(False)
        self.__modify.Enable(False)
        self.__delete.Enable(False)
        # end wxGlade

    # --------------------------------------------------------------------------
    def __do_layout(self):
        # begin wxGlade: CategoriesDlg.__do_layout
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_12 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.VERTICAL)
        label_8 = wx.StaticText(self, -1, "Select one or more categories for the song")
        sizer_11.Add(label_8, 0, wx.ALL, 5)
        sizer_12.Add(self.__list, 1, wx.ALL|wx.EXPAND, 5)
        sizer_13.Add(self.__add, 0, wx.ALL, 5)
        sizer_13.Add(self.__modify, 0, wx.ALL, 5)
        sizer_13.Add(self.__delete, 0, wx.ALL, 5)
        sizer_12.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_11.Add(sizer_12, 1, wx.EXPAND, 0)
        sizer_8.Add(self.button_4, 0, wx.ALL|wx.ALIGN_CENTER_HORIZONTAL, 5)
        sizer_8.Add(self.button_2, 0, wx.ALL, 5)
        sizer_11.Add(sizer_8, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_11)
        sizer_11.Fit(self)
        self.Layout()
        # end wxGlade

    # --------------------------------------------------------------------------
    def SetCurrentSong(self, song):
        """ Gets references belonging to the song, and fills them in the
            list of categories """
        self.__song = song
        for c in song.categories:
            idx = self.__list.FindString(c._name)
            if idx <> wx.NOT_FOUND:
                self.__list.Check(idx, True)

    # --------------------------------------------------------------------------
    def LoadCategories(self):
        """ Loads all categories in the checklist box """
        self.__list.Clear()        
        for c in category_mgr.Get()._list:
            self.__list.Append(c._name)
            
    # --------------------------------------------------------------------------
    def __OnAddCategory(self, event): # wxGlade: CategoriesDlg.<event_handler>
        print "Event handler `__OnAddCategory' not implemented!"
        event.Skip()

    # --------------------------------------------------------------------------
    def __OnModifyCategory(self, event): # wxGlade: CategoriesDlg.<event_handler>
        print "Event handler `__OnModifyCategory' not implemented!"
        event.Skip()

    # --------------------------------------------------------------------------
    def __OnDeleteCategory(self, event): # wxGlade: CategoriesDlg.<event_handler>
        print "Event handler `__OnDeleteCategory' not implemented!"
        event.Skip()

    # --------------------------------------------------------------------------
    def __OnOK(self, event): # wxGlade: CategoriesDlg.<event_handler>
        """ Update all categories in the current song """
        self.__song.categories.clear()
        for i in xrange(0, self.__list.GetCount()):
            c = category_mgr.Get().GetCategoryByName(self.__list.GetString(i))
            if c <> None and self.__list.IsChecked(i):
                self.__song.categories.append(c)
        event.Skip()

# end of class CategoriesDlg


