# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx
import wx.html as html
import time

from wx.lib.pubsub import Publisher
from objs import signals, songs, songfilter
import HtmlInfoGen

startupinfo = """
<html><body>
No song information available
</body></html>
"""

songinfo = """<html><body>
@songinfo@
</body></html>
"""

# begin wxGlade: dependencies
# end wxGlade

class SongInfoWindow(html.HtmlWindow):
    def __init__(self, parent, id):
        html.HtmlWindow.__init__(self, parent, id, style = wx.NO_FULL_REPAINT_ON_RESIZE)
        if "gtk2" in wx.PlatformInfo:
            self.SetStandardFonts()
            
        self.SetPage(startupinfo)
                
        Publisher().subscribe(self.__OnSelectSong, signals.SONG_VIEW_SELECTED)
        Publisher().subscribe(self.__OnSelectSong, signals.SONG_VIEW_UPDATED)

    def __OnSelectSong(self, message):
        """ Select signal when a new song is selected by SongList, we react on it """
        # replace all items and display text
        if message.data == None:
            self.SetPage(startupinfo)
        else:
            if songfilter.Get()._selectedSong == message.data:                   
                self.SetPage(HtmlInfoGen.GenerateHtmlFromSong(template = songinfo, 
                                                              song = message.data))

class CurrSongInfoPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CurrSongInfoPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.__songInfo = SongInfoWindow(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CurrSongInfoPanel.__set_properties
        pass
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CurrSongInfoPanel.__do_layout
        sizer_2 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_2.Add(self.__songInfo, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_2)
        sizer_2.Fit(self)
        # end wxGlade

# end of class CurrSongInfoPanel


