#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:48:11 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx
from GuitarPortfolioFrame import GuitarPortfolioFrame
import appcfg

class GuitarPortfolioApp(wx.App):
    def OnInit(self):
        wx.InitAllImageHandlers()

        self.SetAppName(appcfg.CFG_APPNAME)

        MainFrame = GuitarPortfolioFrame(None, -1, "")
        self.SetTopWindow(MainFrame)
        MainFrame.Show()
        return 1

    def OnExit(self):
        """ Exit the application """
        appcfg.Get().Flush()

# end of class GuitarPortfolioApp

if __name__ == "__main__":
    guitarportfolio = GuitarPortfolioApp(0)
    guitarportfolio.MainLoop()
