# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx

from wx.lib.pubsub import Publisher
from objs import signals, songs, tabs, songfilter
from db import tabs_peer, songs_peer
import db.engine

# begin wxGlade: dependencies
# end wxGlade

# TODO: Revise the whole selection mechanism, it is crooked

class GuitarTabEditPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: GuitarTabEditPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.__addSongTab = wx.Button(self, -1, "&Add >>")
        self.label_21 = wx.StaticText(self, -1, "Enter tablature description")
        self.__tabSelect = wx.ComboBox(self, -1, choices=[], style=wx.CB_DROPDOWN)
        self.__tabText = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.__applySelect = wx.ComboBox(self, -1, choices=["Save To Database", "Revert From Database", "Delete From Database"], style=wx.CB_DROPDOWN|wx.CB_READONLY)
        self.__apply = wx.Button(self, -1, "&Apply")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.__OnAddTab, self.__addSongTab)
        self.Bind(wx.EVT_COMBOBOX, self.__OnTabSelect, self.__tabSelect)
        self.Bind(wx.EVT_BUTTON, self.__OnApply, self.__apply)
        # end wxGlade

        self.__tab = None

        Publisher().subscribe(self.__OnSongSelected, signals.SONG_VIEW_SELECTED)
        Publisher().subscribe(self.__OnTabUpdated, signals.TAB_DB_UPDATED)
        Publisher().subscribe(self.__OnTabRestored, signals.TAB_DB_RESTORED)
        Publisher().subscribe(self.__OnSongSelected, signals.APP_CLEAR)
        Publisher().subscribe(self.__OnTabAdded, signals.TAB_DB_INSERTED)

    #---------------------------------------------------------------------------
    def __set_properties(self):
        # begin wxGlade: GuitarTabEditPanel.__set_properties
        self.__tabText.SetFont(wx.Font(9, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.__applySelect.SetSelection(0)
        # end wxGlade

    #---------------------------------------------------------------------------
    def __do_layout(self):
        # begin wxGlade: GuitarTabEditPanel.__do_layout
        sizer_25 = wx.BoxSizer(wx.VERTICAL)
        sizer_26 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_27 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_27.Add(self.__addSongTab, 0, wx.ALL, 5)
        sizer_27.Add(self.label_21, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_27.Add(self.__tabSelect, 1, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_25.Add(sizer_27, 0, wx.EXPAND, 0)
        sizer_25.Add(self.__tabText, 1, wx.ALL|wx.EXPAND, 5)
        sizer_26.Add(self.__applySelect, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_26.Add(self.__apply, 0, wx.ALL, 5)
        sizer_25.Add(sizer_26, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_25)
        sizer_25.Fit(self)
        # end wxGlade

    #---------------------------------------------------------------------------
    def __OnSongSelected(self, message):
        """ We received an select signal for the song """
        # en/disable the view
        s = message.data
        
        self.__addSongTab.Enable(s <> None)
        self.__tabSelect.Clear()
        self.__tabText.SetValue('')
        self.__applySelect.SetSelection(0)
        self.__tab = None

        # no tabs in the song 
        self.__EnableEditing(self.__tab <> None)            

    #---------------------------------------------------------------------------
    def __OnTabRestored(self, message):
        t = message.data
        if t:
            idx = self.__tabSelect.Append(t._name)
            self.__tabSelect.SetClientData(idx, t)
            
            if not self.__tab:
                self.__DoSelectTab(self.__tabSelect.GetClientData(0))

    #---------------------------------------------------------------------------
    def __OnApply(self, event): # wxGlade: GuitarTabEditPanel.<event_handler>
        if self.__tab <> None:
            if self.__applySelect.GetSelection() == 0:     
                # update in DB
                self.__DoUpdateTab()
                            
            elif self.__applySelect.GetSelection() == 1:  
                 # revert to DB
                self.__DoRevertTab()
                
            elif self.__applySelect.GetSelection() == 2:
                 # delete
                 self.__DoDeleteTab()

            # revert to save, always
            self.__applySelect.SetSelection(0)    
    
    #---------------------------------------------------------------------------
    def __OnTabAdded(self, message):
        if self.__tab:
            # check first if our edit fields are changed
            if (self.__tab._text <> self.__tabText.GetValue()) or \
               (self.__tab._name <> self.__tabSelect.GetStringSelection()):
                
                res = wx.MessageBox('Do you want to save the current tab first?', 'Warning',
                                    wx.ICON_WARNING | wx.YES | wx.NO)
                if res == wx.YES:
                    self.__DoUpdateTab()
                        
        tab = message.data
        # add the tab to the list here
        idx = self.__tabSelect.Append(tab._name)
        self.__tabSelect.SetClientData(idx, tab)    
        self.__DoSelectTab(tab)
    
    #---------------------------------------------------------------------------
    def __DoUpdateTab(self):
        """ Update tab in the DB, and update all fields """
        if self.__tab:
            self.__tab._name = self.__tabSelect.GetValue()
            self.__tab._text = self.__tabText.GetValue()
            
            tp = tabs_peer.TabPeer(db.engine.GetDb())
            tp.Update(self.__tab)
        
    #---------------------------------------------------------------------------
    def __DoRevertTab(self):
        if self.__tab:
            idx = self.__tabSelect.GetSelection()
            self.__tabSelect.SetValue(self.__tab._name)
            self.__tabText.SetValue(self.__tab._text)
            self.__tabSelect.SetSelection(idx)
    
    #---------------------------------------------------------------------------
    def __DoDeleteTab(self):
        if wx.MessageBox('Are you sure you want to delete this tab?', 
                         'Warning', wx.ICON_HAND | wx.YES_NO) == wx.YES:
            # remove it from the collection
            s = songfilter.Get()._selectedSong
            if s and self.__tab:                
                # update relations
                s.tabs.remove(self.__tab)
                slp = songs_peer.SongTabListPeer(db.engine.GetDb())
                slp.Update(s)
                
                # remove tab
                tp = tabs_peer.TabPeer(db.engine.GetDb())
                tp.Delete(self.__tab)

            # find the tab by client data and remove it
            for i in xrange(0, self.__tabSelect.GetCount()):
                if self.__tabSelect.GetClientData(i) == self.__tab:
                    self.__tabSelect.Delete(i)
                    if self.__tabSelect.GetCount() > 0:
                        self.__DoSelectTab(self.__tabSelect.GetClientData(0))
                    else:
                        self.__tab = None
                        self.__EnableEditing(False)
                    break
            
    #---------------------------------------------------------------------------
    def __OnTabUpdated(self, message):
        # find the tab by client data and replace and select
        tab = message.data
        if tab:
            idx = self.__tabSelect.GetSelection()
            for i in xrange(0, self.__tabSelect.GetCount()):
                if self.__tabSelect.GetClientData(i) == tab:
                    self.__tabSelect.SetString(i, tab._name)
                    self.__tabSelect.SetSelection(i)
                    break

    #---------------------------------------------------------------------------
    def __OnAddTab(self, event): # wxGlade: GuitarTabEditPanel.<event_handler>
        # create a new tab to be added
        s = songfilter.Get()._selectedSong
        if s <> None:
            
            # first check if the current tab needs to be stored
            tab = tabs.Tab()
            tab._name = 'Tab #%d' % (s.tabs.count() + 1)
            
            tp = tabs_peer.TabPeer(db.engine.GetDb())
            tp.Update(tab) 
            
            # update the tab collection, so that the song owns the tab
            # from here an add message is emitted which we can use to 
            # sync our list
            s.tabs.append(tab)
            tlp = songs_peer.SongTabListPeer(db.engine.GetDb())
            tlp.Update(s)
            
                                   
    #---------------------------------------------------------------------------
    def __DoSelectTab(self, tab):
        """ Fill edit area with tab data """
        self.__tab = tab
        if tab:
            for i in xrange(0, self.__tabSelect.GetCount()):
                if self.__tabSelect.GetClientData(i) == tab:
                    self.__tabSelect.SetSelection(i)
                    self.__tabText.SetValue(tab._text)
                    self.__EnableEditing(True)
                    return
        
        self.__tabText.SetValue('')
        self.__EnableEditing(False)
        
    #---------------------------------------------------------------------------
    def __EnableEditing(self, status):
        """ Dissalow the user to edit if there is no tab selected or added """
        self.__tabSelect.Enable(status)
        self.__applySelect.Enable(status)
        self.__apply.Enable(status)
        self.__tabText.Enable(status)
        if status == False:
            self.__tabText.SetValue('')
            self.__tabSelect.SetValue('')
            self.__tabSelect.Clear()

    #---------------------------------------------------------------------------
    def __OnTabSelect(self, event): # wxGlade: GuitarTabEditPanel.<event_handler>
        self.__tab = None
        idx = self.__tabSelect.GetSelection()
        if idx == wx.NOT_FOUND:
            self.__EnableEditing(False)
            return
        else:
            self.__DoSelectTab(self.__tabSelect.GetClientData(idx))

# end of class GuitarTabEditPanel


