# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg
import os
import os.path
import sys

import wx
from wx.lib.pubsub import Publisher
import wx.lib.mixins.listctrl as listmix

from images import icon_path_ok, icon_path_not_ok
from objs import signals, linkmgt
import appcfg

# begin wxGlade: dependencies
# end wxGlade

"""

"""
class LinkListCtrl(wx.ListCtrl, listmix.ListCtrlAutoWidthMixin):
    def __init__(self, parent, ID, pos=wx.DefaultPosition, 
                 size = wx.DefaultSize):
        
        wx.ListCtrl.__init__(self, parent, ID, pos, size, style = wx.LC_REPORT | 
                                                                  wx.BORDER_NONE | 
                                                                  wx.LC_EDIT_LABELS | 
                                                                  wx.LC_SORT_ASCENDING)
        listmix.ListCtrlAutoWidthMixin.__init__(self)
        
        # create columns for links listctrl
        self.InsertColumn(0, "Name", width = 200)
        self.InsertColumn(1, "Type", width = 75)        
        self.InsertColumn(2, "Link")
        
class LinksPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LinksPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.label_32 = wx.StaticText(self, -1, "Base path:")
        self.__pathOK = wx.StaticBitmap(self, -1, wx.NullBitmap)
        self.__basePath = wx.StaticText(self, -1, "d:\\my music\\Everlast - Whitey Ford Sings The Blues")
        self.__createPath = wx.Button(self, -1, "&Create")
        self._links = LinkListCtrl(self, -1)
        self.__refreshLinks = wx.Button(self, -1, "&Refresh")
        self.__addURL = wx.Button(self, -1, "&Add URL")
        self.__ignoreFile = wx.Button(self, -1, "&Ignore File")
        self.__manageLinks = wx.Button(self, -1, "&Manage ...")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.__OnCreateBasePath, self.__createPath)
        self.Bind(wx.EVT_BUTTON, self.__OnRefresh, self.__refreshLinks)
        self.Bind(wx.EVT_BUTTON, self.__OnAddURL, self.__addURL)
        self.Bind(wx.EVT_BUTTON, self.__OnIgnoreFile, self.__ignoreFile)
        self.Bind(wx.EVT_BUTTON, self.__OnManageFiles, self.__manageLinks)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: LinksPanel.__set_properties
        self.__pathOK.SetMinSize((16, 16))
        self.__basePath.SetFont(wx.Font(8, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self._links.SetMinSize((-1,200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: LinksPanel.__do_layout
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_42 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_29 = wx.BoxSizer(wx.VERTICAL)
        sizer_3_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_43 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_43.Add(self.label_32, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_43.Add(self.__pathOK, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_43.Add(self.__basePath, 1, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_43.Add(self.__createPath, 0, wx.ALL, 5)
        sizer_3.Add(sizer_43, 0, wx.EXPAND, 0)
        sizer_3_copy.Add(self._links, 1, wx.EXPAND, 0)
        sizer_42.Add(sizer_3_copy, 1, wx.EXPAND, 0)
        sizer_29.Add(self.__refreshLinks, 0, wx.ALL, 5)
        sizer_29.Add(self.__addURL, 0, wx.ALL, 5)
        sizer_29.Add(self.__ignoreFile, 0, wx.ALL, 5)
        sizer_29.Add(self.__manageLinks, 0, wx.ALL, 5)
        sizer_42.Add(sizer_29, 0, wx.EXPAND, 5)
        sizer_3.Add(sizer_42, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_3)
        sizer_3.Fit(self)
        # end wxGlade

    def __OnCreateBasePath(self, event): # wxGlade: LinksPanel.<event_handler>
        print "Event handler `__OnCreateBasePath' not implemented!"
        event.Skip()

    def __OnRefresh(self, event): # wxGlade: LinksPanel.<event_handler>
        print "Event handler `__OnRefresh' not implemented!"
        event.Skip()

    def __OnAddURL(self, event): # wxGlade: LinksPanel.<event_handler>
        print "Event handler `__OnAddURL' not implemented!"
        event.Skip()

    def __OnIgnoreFile(self, event): # wxGlade: LinksPanel.<event_handler>
        print "Event handler `__OnIgnoreFile' not implemented!"
        event.Skip()

    def __OnManageFiles(self, event): # wxGlade: LinksPanel.<event_handler>
        print "Event handler `__OnManageFiles' not implemented!"
        event.Skip()

# end of class LinksPanel


