# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg
import os
import os.path
import sys

import wx
from wx.lib.pubsub import Publisher
import wx.lib.mixins.listctrl as listmix
import wx.xrc as xrc

from images import icon_path_ok, icon_path_not_ok
from objs import signals, linkmgt
import appcfg, xmlres
                
class LinksPanel(wx.Panel):
    def __init__(self, parent, id = -1):
        pre = wx.PrePanel()
        xmlres.Res().LoadOnPanel(pre, parent, "EditLinkDialog")
        self.PostCreate(pre)

        # TODO: Make a wx.ListCtrl, listmix.ListCtrlAutoWidthMixin custom class for XRC
        self._links = xrc.XRCCTRL(self, "ID_LINK_LIST")
        self._links.InsertColumn(0, "Name", width = 200)
        self._links.InsertColumn(1, "Type", width = 75)        
        self._links.InsertColumn(2, "Link", width = 300)
        self.__basePath = xrc.XRCCTRL(self, "ID_LINK_PATH")
        self.__pathOK = xrc.XRCCTRL(self, "ID_PATH_STATUS")
        
        self.Bind(wx.EVT_BUTTON, self.__OnCreateBasePath, xrc.XRCCTRL(self, "ID_BTN_CREATE"))
        self.Bind(wx.EVT_BUTTON, self.__OnRefresh, xrc.XRCCTRL(self, "ID_BTN_REFRESH"))
        self.Bind(wx.EVT_BUTTON, self.__OnAddURL, xrc.XRCCTRL(self, "ID_BTN_ADD"))
        self.Bind(wx.EVT_BUTTON, self.__OnIgnoreFile, xrc.XRCCTRL(self, "ID_BTN_IGNORE"))
        self.Bind(wx.EVT_BUTTON, self.__OnManageFiles, xrc.XRCCTRL(self, "ID_BTN_EDIT"))
        
    def __OnCreateBasePath(self, event):
        print "Event handler `__OnCreateBasePath' not implemented!"
        event.Skip()

    def __OnRefresh(self, event): 
        print "Event handler `__OnRefresh' not implemented!"
        event.Skip()

    def __OnAddURL(self, event): 
        print "Event handler `__OnAddURL' not implemented!"
        event.Skip()

    def __OnIgnoreFile(self, event): 
        print "Event handler `__OnIgnoreFile' not implemented!"
        event.Skip()

    def __OnManageFiles(self, event): 
        print "Event handler `__OnManageFiles' not implemented!"
        event.Skip()


