# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx
import wx.html as html
from wx.lib.pubsub import Publisher
import wx.xrc as xrc

from objs import songs
import HtmlInfoGen
import xmlres, wikiparser, viewmgr

# begin wxGlade: dependencies
# end wxGlade

class LyricInfoPanel(wx.Panel):
    def __init__(self, parent, id = -1):
        pre = wx.PrePanel()
        xmlres.Res().LoadOnPanel(pre, parent, "LyricsInfoPanel")
        self.PostCreate(pre)

        self.__lyricsInfo = xrc.XRCCTRL(self, "ID_LYRICSWINDOW")
        if "gtk2" in wx.PlatformInfo:
            self.__lyricsInfo.SetStandardFonts()
            
        self.__lyricsInfo.SetPage('')

        # hook up a select signal
        Publisher().subscribe(self.__OnSelectSong, viewmgr.SIGNAL_SONG_SELECTED)
        Publisher().subscribe(self.__OnSelectSong, viewmgr.SIGNAL_SONG_UPDATED)
        Publisher().subscribe(self.__OnSelectSong, viewmgr.SIGNAL_CLEAR_DATA)
        
    # --------------------------------------------------------------------------
    def __OnSelectSong(self, message):
        """ Select signal when a new song is selected by SongList, we react on it """
        # replace all items and display text
        song = message.data
        parser = wikiparser.WikiParser()
        if song:
            self.__lyricsInfo.SetPage(parser.Parse(song._lyrics))
        else:                   
            self.__lyricsInfo.SetPage('')
