# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx
import wx.html as html
from wx.lib.pubsub import Publisher
import wx.xrc as xrc

from objs import signals, songs
import HtmlInfoGen
import xmlres

# begin wxGlade: dependencies
# end wxGlade

lyricinfo = """<html><body>
<pre>@lyrics@</pre>
</body></html>
"""

class LyricInfoPanel(wx.Panel):
    def __init__(self, parent, id = -1):
        pre = wx.PrePanel()
        xmlres.Res().LoadOnPanel(pre, parent, "LyricsInfoPanel")
        self.PostCreate(pre)

        self.__lyricsInfo = xrc.XRCCTRL(self, "ID_LYRICSWINDOW")
        if "gtk2" in wx.PlatformInfo:
            self.__lyricsInfo.SetStandardFonts()
            
        self.__lyricsInfo.SetPage('')

        # hook up a select signal
        Publisher().subscribe(self.__OnSelectSong, signals.SONG_VIEW_SELECTED)
        Publisher().subscribe(self.__OnSelectSong, signals.SONG_VIEW_UPDATED)
        Publisher().subscribe(self.__OnSelectSong, signals.APP_CLEAR)
        
    # --------------------------------------------------------------------------
    def __OnSelectSong(self, message):
        """ Select signal when a new song is selected by SongList, we react on it """
        # replace all items and display text
        if message.data:
            self.__lyricsInfo.SetPage(HtmlInfoGen.GenerateHtmlFromSong(template = lyricinfo, 
                                      song = message.data))
        else:                   
            self.__lyricsInfo.SetPage('')


