# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx
import wx.html as html
from wx.lib.pubsub import Publisher

from objs import signals, songs
import HtmlInfoGen

# begin wxGlade: dependencies
# end wxGlade

lyricinfo = """<html><body>
<pre>@lyrics@</pre>
</body></html>
"""

class LyricInfoWindow(html.HtmlWindow):
    def __init__(self, parent, id):
        html.HtmlWindow.__init__(self, parent, id, style = wx.NO_FULL_REPAINT_ON_RESIZE)
        if "gtk2" in wx.PlatformInfo:
            self.SetStandardFonts()
            
        self.SetPage('')
        
        # hook up a select signal
        Publisher().subscribe(self.__OnSelectSong, signals.SONG_VIEW_SELECTED)
        Publisher().subscribe(self.__OnSelectSong, signals.SONG_VIEW_UPDATED)
        Publisher().subscribe(self.__OnSelectSong, signals.APP_CLEAR)
        
    # --------------------------------------------------------------------------
    def __OnSelectSong(self, message):
        """ Select signal when a new song is selected by SongList, we react on it """
        # replace all items and display text
        if message.data:
            self.SetPage(HtmlInfoGen.GenerateHtmlFromSong(template = lyricinfo, 
                                                          song = message.data))
        else:                   
            self.SetPage('')

class LyricInfoPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: LyricInfoPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.__lyricsInfo = LyricInfoWindow(self, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    # --------------------------------------------------------------------------
    def __set_properties(self):
        # begin wxGlade: LyricInfoPanel.__set_properties
        pass
        # end wxGlade

    # --------------------------------------------------------------------------
    def __do_layout(self):
        # begin wxGlade: LyricInfoPanel.__do_layout
        sizer_22 = wx.BoxSizer(wx.VERTICAL)
        sizer_22.Add(self.__lyricsInfo, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_22)
        sizer_22.Fit(self)
        # end wxGlade

# end of class LyricInfoPanel


