# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx

# begin wxGlade: dependencies
# end wxGlade

class OptionsDlg(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: OptionsDlg.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.notebook_1 = wx.Notebook(self, -1, style=0)
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, -1)
        self.label_37_copy = wx.StaticText(self.notebook_1_pane_1, -1, "Base path for relative file links")
        self.__absPath = wx.TextCtrl(self.notebook_1_pane_1, -1, "")
        self.__browsePath = wx.Button(self.notebook_1_pane_1, -1, "...")
        self.__okButton = wx.Button(self, wx.ID_OK, "")
        self.__cancelButton = wx.Button(self, wx.ID_CANCEL, "")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.__OnBrowsePath, self.__browsePath)
        self.Bind(wx.EVT_BUTTON, self.__OnOK, self.__okButton)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: OptionsDlg.__set_properties
        self.SetTitle("Options")
        self.SetSize((480, 280))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: OptionsDlg.__do_layout
        sizer_44 = wx.BoxSizer(wx.VERTICAL)
        sizer_47 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_48_copy = wx.BoxSizer(wx.VERTICAL)
        sizer_49_copy = wx.BoxSizer(wx.HORIZONTAL)
        sizer_48_copy.Add(self.label_37_copy, 0, wx.ALL, 5)
        sizer_49_copy.Add(self.__absPath, 1, wx.LEFT|wx.RIGHT|wx.BOTTOM, 5)
        sizer_49_copy.Add(self.__browsePath, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_48_copy.Add(sizer_49_copy, 0, wx.EXPAND, 0)
        self.notebook_1_pane_1.SetSizer(sizer_48_copy)
        self.notebook_1.AddPage(self.notebook_1_pane_1, "Link Items")
        sizer_44.Add(self.notebook_1, 1, wx.EXPAND, 0)
        sizer_47.Add(self.__okButton, 0, wx.ALL, 5)
        sizer_47.Add(self.__cancelButton, 0, wx.ALL, 5)
        sizer_44.Add(sizer_47, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        self.SetSizer(sizer_44)
        self.Layout()
        # end wxGlade

    def __OnBrowsePath(self, event): # wxGlade: OptionsDlg.<event_handler>
        print "Event handler `__OnBrowsePath' not implemented!"
        event.Skip()

    def __OnOK(self, event): # wxGlade: OptionsDlg.<event_handler>
        print "Event handler `__OnOK' not implemented!"
        event.Skip()

# end of class OptionsDlg


