# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx

# begin wxGlade: dependencies
# end wxGlade

class ProgressPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ProgressPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.label_12 = wx.StaticText(self, -1, "Estimated % of accuracy")
        self.__accuracy = wx.Slider(self, -1, 0, 0, 10, style=wx.SL_HORIZONTAL|wx.SL_AUTOTICKS)
        self.__accuracyNr = wx.StaticText(self, -1, "[10]")
        self.label_13 = wx.StaticText(self, -1, "Estimated % completed")
        self.__estimated = wx.Slider(self, -1, 0, 0, 10, style=wx.SL_HORIZONTAL|wx.SL_AUTOTICKS)
        self.__estimatedNr = wx.StaticText(self, -1, "[10]")
        self.label_14 = wx.StaticText(self, -1, "Total progress")
        self.__percent = wx.StaticText(self, -1, "100%")
        self.static_line_1 = wx.StaticLine(self, -1)
        self.label_16 = wx.StaticText(self, -1, "Add")
        self.__minutes = wx.TextCtrl(self, -1, "30")
        self.__minuteButton = wx.Button(self, -1, "+")
        self.label_19 = wx.StaticText(self, -1, "minutes studytime")
        self.static_line_3 = wx.StaticLine(self, -1, style=wx.LI_VERTICAL)
        self.label_17 = wx.StaticText(self, -1, "Change status to")
        self.__status = wx.Choice(self, -1, choices=["In Progress", "Not Practicing", "Completed!"])
        self.__statusButton = wx.Button(self, -1, "&Change")
        self.static_line_2 = wx.StaticLine(self, -1)
        self.label_18 = wx.StaticText(self, -1, "Enter details to be logged while studying like hard parts, key moments, etc")
        self.__log = wx.TextCtrl(self, -1, "", style=wx.TE_MULTILINE)
        self.__submitButton = wx.Button(self, -1, "&Submit")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_COMMAND_SCROLL_THUMBRELEASE, self.__OnAccuracyEnd, self.__accuracy)
        self.Bind(wx.EVT_COMMAND_SCROLL_THUMBTRACK, self.__OnAccuracyScroll, self.__accuracy)
        self.Bind(wx.EVT_COMMAND_SCROLL_THUMBRELEASE, self.__OnCompletedEnd, self.__estimated)
        self.Bind(wx.EVT_COMMAND_SCROLL_THUMBTRACK, self.__OnCompletedScroll, self.__estimated)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ProgressPanel.__set_properties
        self.__accuracyNr.SetFont(wx.Font(9, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.__estimatedNr.SetFont(wx.Font(9, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        self.__percent.SetFont(wx.Font(16, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.__minutes.SetMinSize((50, -1))
        self.__minuteButton.SetMinSize((50, -1))
        self.__status.SetSelection(0)
        self.__log.SetFont(wx.Font(9, wx.MODERN, wx.NORMAL, wx.NORMAL, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ProgressPanel.__do_layout
        sizer_17 = wx.BoxSizer(wx.VERTICAL)
        sizer_20 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_19 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_18.Add(self.label_12, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_18.Add(self.__accuracy, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_18.Add(self.__accuracyNr, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_18.Add(self.label_13, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_18.Add(self.__estimated, 0, wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_18.Add(self.__estimatedNr, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_18.Add(self.label_14, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_18.Add(self.__percent, 0, wx.ALL, 5)
        sizer_17.Add(sizer_18, 0, wx.EXPAND, 0)
        sizer_17.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_19.Add(self.label_16, 0, wx.LEFT|wx.TOP|wx.BOTTOM|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_19.Add(self.__minutes, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_19.Add(self.__minuteButton, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_19.Add(self.label_19, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_19.Add(self.static_line_3, 0, wx.EXPAND, 0)
        sizer_19.Add(self.label_17, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_19.Add(self.__status, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_19.Add(self.__statusButton, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_17.Add(sizer_19, 0, wx.EXPAND, 0)
        sizer_17.Add(self.static_line_2, 0, wx.EXPAND, 0)
        sizer_17.Add(self.label_18, 0, wx.LEFT|wx.RIGHT|wx.TOP, 5)
        sizer_20.Add(self.__log, 1, wx.ALL|wx.EXPAND, 5)
        sizer_20.Add(self.__submitButton, 0, wx.ALL|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_17.Add(sizer_20, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_17)
        sizer_17.Fit(self)
        # end wxGlade

    def __OnAccuracyEnd(self, event): # wxGlade: ProgressPanel.<event_handler>
        print "Event handler `__OnAccuracyEnd' not implemented!"
        event.Skip()

    def __OnAccuracyScroll(self, event): # wxGlade: ProgressPanel.<event_handler>
        print "Event handler `__OnAccuracyScroll' not implemented!"
        event.Skip()

    def __OnCompletedEnd(self, event): # wxGlade: ProgressPanel.<event_handler>
        print "Event handler `__OnCompletedEnd' not implemented!"
        event.Skip()

    def __OnCompletedScroll(self, event): # wxGlade: ProgressPanel.<event_handler>
        print "Event handler `__OnCompletedScroll' not implemented!"
        event.Skip()

# end of class ProgressPanel


