# -*- coding: iso-8859-1 -*-
# generated by wxGlade 0.5 on Sun May 13 11:47:41 2007 from D:\personal\src\GuitarPortfolio\branches\db_revival\gui\guitarportfolio.wxg

import wx
from wx.lib.pubsub import Publisher

from objs import songs, signals, songfilter
import appcfg


# begin wxGlade: dependencies
# end wxGlade

class SongFilterPanel(wx.Panel):
    def __init__(self, *args, **kwds):
        # begin wxGlade: SongFilterPanel.__init__
        kwds["style"] = wx.TAB_TRAVERSAL
        wx.Panel.__init__(self, *args, **kwds)
        self.label_10 = wx.StaticText(self, -1, "Filter by progress")
        self.__progressFilter = wx.Choice(self, -1, choices=["All Progress", "In Progress", "Not Practicing", "Completed!", "TODO"])
        self.label_22 = wx.StaticText(self, -1, "Filter by difficulty")
        self.__difficulty = wx.Choice(self, -1, choices=["Not Applicable", "Easy", "Normal", "Intermediate", "Advanced", "Hard", "Impossible"])
        self.__strictDifficulty = wx.CheckBox(self, -1, "Also show songs matching a lower difficulty")
        self.static_line_4 = wx.StaticLine(self, -1)
        self.label_23 = wx.StaticText(self, -1, "Filter by category")
        self.__cats = wx.CheckListBox(self, -1)
        self.__categoriesAndFilter = wx.CheckBox(self, -1, "Only show songs that match all selected categories")

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_CHOICE, self.__OnFilterSongs, self.__progressFilter)
        self.Bind(wx.EVT_CHOICE, self.__OnSelectDifficulty, self.__difficulty)
        self.Bind(wx.EVT_CHECKBOX, self.__OnShowMatchingLowerDifficulty, self.__strictDifficulty)
        self.Bind(wx.EVT_CHECKBOX, self.__OnShowCategoriesAND, self.__categoriesAndFilter)
        # end wxGlade

        # subscribe to changes
        Publisher().subscribe(self.__OnChangeCats, signals.SONG_DB_CAT_UPDATED)
        Publisher().subscribe(self.__OnAppReady, signals.APP_READY)
        Publisher().subscribe(self.__OnClear, signals.APP_CLEAR)

        self.Bind(wx.EVT_CHECKLISTBOX, self.__OnItemChecked, self.__cats)

    #---------------------------------------------------------------------------
    def __set_properties(self):
        # begin wxGlade: SongFilterPanel.__set_properties
        self.__progressFilter.SetSelection(0)
        self.__difficulty.SetSelection(0)
        # end wxGlade

    #---------------------------------------------------------------------------
    def __do_layout(self):
        # begin wxGlade: SongFilterPanel.__do_layout
        sizer_28 = wx.BoxSizer(wx.VERTICAL)
        sizer_28.Add(self.label_10, 0, wx.ALL, 5)
        sizer_28.Add(self.__progressFilter, 0, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizer_28.Add(self.label_22, 0, wx.ALL, 5)
        sizer_28.Add(self.__difficulty, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM|wx.EXPAND|wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_28.Add(self.__strictDifficulty, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 5)
        sizer_28.Add(self.static_line_4, 0, wx.ALL|wx.EXPAND, 5)
        sizer_28.Add(self.label_23, 0, wx.LEFT|wx.RIGHT|wx.BOTTOM, 5)
        sizer_28.Add(self.__cats, 1, wx.LEFT|wx.RIGHT|wx.EXPAND, 5)
        sizer_28.Add(self.__categoriesAndFilter, 0, wx.ALL, 5)
        self.SetSizer(sizer_28)
        sizer_28.Fit(self)
        # end wxGlade

    #---------------------------------------------------------------------------
    def __OnFilterSongs(self, event): # wxGlade: SongFilterPanel.<event_handler>
        crits = [songfilter._CRIT_STATUS_ALL, 
                 songs.SS_STARTED, 
                 songs.SS_POSTPONED, 
                 songs.SS_COMPLETED, 
                 songs.SS_NOT_STARTED]
        idx = self.__progressFilter.GetSelection()
        songfilter.Get().ChangeStatusCriteria(crits[idx])
        appcfg.Get().WriteInt(appcfg.CFG_PROGRESS, idx)

    #---------------------------------------------------------------------------
    def __OnSelectDifficulty(self, event): # wxGlade: SongFilterPanel.<event_handler>
        crits = [songfilter._CRIT_STATUS_ALL, 
                 songs.SD_EASY,
                 songs.SD_NORMAL,
                 songs.SD_INTERMEDIATE,
                 songs.SD_ADVANCED,
                 songs.SD_HARD,
                 songs.SD_IMPOSSIBLE]
        idx = self.__difficulty.GetSelection()
        songfilter.Get().ChangeDifficultyCriteria(crits[idx])
        appcfg.Get().WriteInt(appcfg.CFG_DIFFICULTY, idx)

    #---------------------------------------------------------------------------
    def __OnChangeCats(self, message):
        self.__PopulateCategories()
       
    #---------------------------------------------------------------------------
    def __PopulateCategories(self):
        """ Fill checklisbox with only the categories being used, keep some kind
            of shadow check state because the stupid wx.CheckListCtrl hogs the 
            client data """
        self.__cats.Clear()
        self.__catsClientData = []
        cats = songfilter.Get().GetUsedCategories()
        criteria = songfilter.Get()._critCategories
        for c in cats:
            idx = self.__cats.Append(c._name)
            # keep a list of associated data
            self.__catsClientData.append(c)
            self.__cats.Check(idx, c in criteria)
                       
    #---------------------------------------------------------------------------
    def __OnItemChecked(self, event):
        # compose list of checked items
        selcats = []
        for i in xrange(self.__cats.GetCount()):
            if self.__cats.IsChecked(i):
                selcats.append(self.__catsClientData[i])
        songfilter.Get().ChangeCategoriesCriteria(selcats)

    #---------------------------------------------------------------------------
    def __OnShowMatchingLowerDifficulty(self, event): # wxGlade: SongFilterPanel.<event_handler>
        chk = self.__strictDifficulty.GetValue()
        songfilter.Get().ChangeDifficultyCriteriaLO(chk)
        appcfg.Get().WriteInt(appcfg.CFG_LOWERDIFFICULTY, 1 if chk else 0)

    #---------------------------------------------------------------------------
    def __OnShowCategoriesAND(self, event): # wxGlade: SongFilterPanel.<event_handler>
        chk = self.__categoriesAndFilter.GetValue()
        songfilter.Get().ChangeCategoriesCriteriaAND(chk)
        appcfg.Get().WriteInt(appcfg.CFG_CATEGORIESAND, 1 if chk else 0)

    #---------------------------------------------------------------------------
    def __OnAppReady(self, message):
        """ App is ready with data, we can initialize our last viewstate """
        cfg = appcfg.Get()
        if cfg.HasGroup('filter'):
            # read the difficulty
            idx = cfg.ReadInt(appcfg.CFG_DIFFICULTY, 0)
            self.__difficulty.SetSelection(idx)
            self.__OnSelectDifficulty(event = None)
            
            # read the song status
            idx = cfg.ReadInt(appcfg.CFG_PROGRESS, 0)
            self.__progressFilter.SetSelection(idx)
            self.__OnFilterSongs(event = None)
            
            # categories AND
            self.__categoriesAndFilter.SetValue(True if cfg.ReadInt(appcfg.CFG_CATEGORIESAND, 0) <> 0 else False)
            self.__OnShowCategoriesAND(event = None)
            # lower difficulty
            self.__strictDifficulty.SetValue(True if cfg.ReadInt(appcfg.CFG_LOWERDIFFICULTY, 0) <> 0 else False)
            self.__OnShowMatchingLowerDifficulty(event = None)
        
        self.__PopulateCategories()

    #---------------------------------------------------------------------------
    def __OnClear(self, message):
        """ Clear the views, a DB change is probably in order """
        self.__cats.Clear()
        self.__catsClientData = []
            
# end of class SongFilterPanel


